### PR TITLE
V.has with Pair

### PR DESCRIPTION
**Pull request by dkrieg**

### CODE REVIEW

**Comment by joan38** [comment]
I like

**Comment by joan38** [comment]
@dkrieg I was going to merge this why did you close it?

**Comment by dkrieg** [comment]
It should that there were merge conflicts.. I was going to correct them and resubmit.

**Comment by joan38** [comment]
Yes sorry it me who introduced the conflicts.
You can merge and push to the branch it automatically updates the PR.

**Comment by dkrieg** [comment]
still new to the git process...sorry.

**Comment by joan38** [comment]
No worries ;)

**Comment by dkrieg** [comment]
btw, is there a chat room we can use to exchange ideas or is it just through these comments on PR or the general gremlin-users google group?

**Comment by joan38** [comment]
I think you are right only github or the general gremlin user google group.

**Comment by mpollmeier** [comment]
Agreed, a chat can be useful, I just created a gitter channel for this repo: 
https://gitter.im/mpollmeier/gremlin-scala

**Pull request merged**
