### PR TITLE
remove @label(NonLiteral.Value) due to it's bad performance

### PR DESCRIPTION
**Pull request by mpollmeier**
fixes https://github.com/mpollmeier/gremlin-scala/issues/288

### CODE REVIEW

**Comment by mpollmeier** [comment]
@timw @jeremysears

**Comment by jeremysears** [comment]
LGTM.

**Comment by mpollmeier** [comment]
sonatype seems down again, will retrigger the build later
```
[error] java.io.IOException: Failure:java.util.concurrent.ExecutionException: org.apache.http.NoHttpResponseException: oss.sonatype.org:443 failed to respond
```

**Comment by mpollmeier** [comment]
this is released as 3.4.4.1

**Pull request merged**
