### PR TITLE
Marshalling macros

### PR DESCRIPTION
**Pull request by joan38**
Hi,

I did a lot of changes:
- Marshalling with our own Macros
- This is NOT marshalling nested classes
- The name of the class is used for the label
- Introduced the `@label` to use an attribute as a label
- save(cc) is now addVertex(cc) (this needs to go explicit ScalaGraph but we already recommande to go explicit)
- load is now toCC
- All of the above is working on edges
- toCC is now implemented on ScalaVertex or ScalaEdge but we keep toCC in package in order to load in the query.
- The following `v1 --- MyCC("myLabel", "some string") --> v2` is working
- The following `v1 <-- MyCC("myLabel", "some string") --- v2` is working
- The following `v1 <-- "label" --- v2` is working
- The following `v1 <-- ("label", Map("key", "value")) --- v2` is working
- The following `v1 <-- "label" --> v2` is working
- Introduced the .asScala and .asJava
- Ditched away GS case class and GremlinScala(Graph) as this is confusing with the query objects and too many ways to switch from a Graph to a ScalaGraph.
- Ditched away the unwrap functions as this is causing too much unwanted unwrap and avoid the type safety.
- gs.graph and gs.asJava are now returning the graph type (ex: TinkerGraph)

Cheers

### CODE REVIEW

**Comment by joan38** [comment]
Leave this to me for now as the macros I wrote are for 2.11
This needs more than just adding the compiler plugin.

**Comment by omidb** [comment]
@joan38 I think the previous implementation for vertex was better, it supports more complex architecture of nested classes. We can use the same thing to add Edge support. The same thing would completely work for Edges without any annotation.

**Comment by joan38** [comment]
How would you point which attribute is the one to use for the label?
We can add the nested class support on this one too but it's seems that it doesn't work on most of DBs for now.

**Comment by joan38** [comment]
The next improvements are:
- Switch the deprecated reflection methods to 2.11 methods
- Add the `@id` support
- Support nested case classes in a better thought way in order to make it work with more than one DB implementation

@mpollmeier can you check if the sbt publish settings are right as we now have 2 subproject (2 compilation unit needed by macros).
Also I think we need to tweak Travis to drop 2.10 support.

Cheers

**Comment by omidb** [comment]
@joan38 @mpollmeier This is not really constructive that we merge #80 and then delete everything and merge #81 .

**Comment by joan38** [comment]
@omidb I understand we dropped #73 for #81 and we lost the nested case class persisting that is supported on OrientDB and TinkerGraph only.
But I believe we have now more control on the implementation as we don't use shapeless and we are therefore able to have `@label` or the name of the class as a label (like it was doing before in reflexion). I'm also expected to extends it on `@id` to set the id and probably some `@indexed` or so.
But I might be wrong and we might actually be able to implement those functionalities with shapeless.

**Comment by mpollmeier** [comment]
two things:

1) If I have the choice between macros and shapeless I'd always go for shapeless. One reason is that it's less magic and IDEs can actually help developers figure out what's going on. A second reason is that once scala 2.12 is released we may be in trouble with the macros, as they will likely not be compatible across scala versions. Can we achieve the same (or slightly less) with shapeless?

2) Scala 2.10 is broken in this PR as your macros seem to be incompatible with it. That's intentional I guess as we discussed it in another issue, but we should remove it from the build and the .travis.yml file then. Now master is 'red', that's a really bad outcome. Please don't merge anything to master that has a failed build. Can you please either remove 2.10 support (fine with me) or revert back to shapeless?
https://travis-ci.org/mpollmeier/gremlin-scala

**Comment by joan38** [comment]
1. @omidb I leave you check if this is possible as I don't really get what's happening [here](https://github.com/omidb/gremlin-scala/blob/9bdbf37c2ca7c41a0b37249fe91367fd597cd606/src/main/scala/gremlin/scala/SafeMapper.scala) and can't find any documentation.  
Also I don't think any big change is scheduled in 2.12 for macros as a change already happened in 2.11: the blackbox/whitebox separation, we are using blackbox in our case which gives good support by IDEs.
2. Dropped 2.10. Sorry I didn't know that Travis was configured directly from the file [.travis.yml](https://github.com/mpollmeier/gremlin-scala/blob/master/.travis.yml)

**Comment by omidb** [comment]
@mpollmeier @joan38 
We are already getting everything we need with Shapeless in #80 . Here is the difference between these two approaches:
1. Shapeless: we get a better representation for Nested or Flat case classes without using any Macros. It's building in 2.10 and 2.11 and will be working in 2.12! Some DBs support nested features: OrientDB, TInkerGraph and I think GraphX! but all support flat structure!
2. Macros: The only difference which is also possible to implement (and I didn't know we need it!) in Shapeless and is in the Macro version is the ability to add annotation for `label`.

My vote obviously is rolling back to #80 and start a conversation about WHAT we need first and schedule it to do it..

**Comment by joan38** [comment]
The #81 also support nested case classes in TinkerGraph and should be in OrientDB too, I'll try tonight and let you know.

The second point is interesting, I'd like to see how it works. Do you have more documentation about the shapeless functionality you used because all of that looks like magic to me with all implicits?
I'd like also to be able to enable indexing on fields with something like `@indexed(<settings for the index>)` do you think we will be able to do that with shapeless?
I don't agree with you that labels are not needed in a graph DB.

**Comment by joan38** [comment]
The nested class is actually working in OrientDB with this implementation.

**Comment by omidb** [comment]
The difference is the serialization: In the case of nested case classes here you will save a vertex like this:
```scala
val jack = Person("jack", Address("Jefferson",11111))
\\Vertex("name" -> "jack", "address" -> Address("Jefferson",11111))
```
With #80 you will get:
```scala
val jack = Person("jack", Address("Jefferson",11111))
\\Vertex("name" -> "jack", "address" -> Map("street" ->"Jefferson", "zip" -> 11111))
```
which in the second one you can access to the DB with SQL or whatever other driver because they have been stored as `key\value` not serialized objects!

**Comment by omidb** [comment]
On the other hand in many times you don't have access to case class to annotate it! When it comes from a lib or something, so this is why annotation is not very famous in Scala community

**Comment by joan38** [comment]
@omidb 1st message: This is very specific to OrientDB.
@omidb 2nd message: You don't HAVE to use the annotations, you just can if you want to profit from the feature, it will take the name of the class otherwise (like it was doing in the first version).
I'm of course open to a better solution.

Slick went for annotations in the passed with [direct embedding](http://slick.typesafe.com/doc/3.0.1/direct-embedding.html), and finally deprecated them to avoid macro based marshalling and I think for more readable case classes.
But I think in our case we don't have enough to use a separate mapping definition class [like they do now](http://slick.typesafe.com/doc/3.0.1/schemas.html).

I have implemented the `@id` yesterday and I'm currently moving the `@label` on the class instead of the parameter. So it does something like that:

    @label("my custom label")
    case class Example(
      @id id: String,
      s: String,
      i: Int
    )

I will do a PR soon with this change.

I have been thinking for the `@indexed` but indexing is very implementation specific, so I'm thinking to have only an interface annotation where each implementations embed there indexing logic.

**Comment by mpollmeier** [comment]
Ok so it sounds like we have two good solutions here, that's a good thing. So that we can decide which one is better (or if we even want to keep both) let me try to summarise: 

1) Forward compatibility with future versions of scala:
* Acc to http://docs.scala-lang.org/overviews/macros/blackbox-whitebox.html `Scala 2.12 will not see any changes to macros`. Looking forward to future versions of Scala I can see a higher likelihood of macros changing, but also of giving us more power more easily. This one is a draw for me. 

2) IDE support
* While it's good to use black box macros, IDE support is note quite there yet apparently. Advantage for shapeless on this one: implicits are a normal language feature
http://stackoverflow.com/questions/22047492/how-to-make-intellij-idea-recognise-code-created-by-macros

3) Simplicity and maintainability of the solution:
* both involve a fair bit of magic, my personal preference is shapeless as it's all within the language, but I can see advantages for macros in the future. 

4) Support for nested types
* I'd prefer the result from the macro, i.e. as above: `\\Vertex("name" -> "jack", "address" -> Address("Jefferson",11111))` rather than a mixture of case classes and Maps for level 2 and below

5) Allowing to store all attributes incl. id and label
* from the above it sounds like the macro solution can do it. @omidb would it be possible to do the same with shapeless? I agree with @joan38 both of these are necessary as they are essential parts of TP3 vertices

Did I miss any important arguments or misinterpret anything? I want us to use the best solution and am very thankful to both of you for providing great alternatives and being part of this discussion!

**Comment by joan38** [comment]
I'd like to add that I am happy to use the shapeless version as long as we can implement some kind of equivalent to the point 5)

**Comment by omidb** [comment]
I want to mention one point about @mpollmeier point 4, saving nested data as:

```scala
val jack = Person("jack", Address("Jefferson",11111))
\\Vertex("name" -> "jack", "address" -> Address("Jefferson",11111))
```
with this structure if you need to access specific value in address, the only way would be using `gremlin-scala` because you need deserialize the Address and you need to have class definition. But using nested Maps you can also query using SQL or any other driver (e.g. Python, ...) because it's defined type in that DB. Or even using Tinkerpop steps would be easier because it's just `key/value` pair and you might be able to write `g.V(v).properties("name").hasValue("marko")` which you cannot do the same using serialized Address. This is the first reason that I tried to do it with nested map structure.

@joan38 @mpollmeier about 5) I think we might be able to add this using shapeless with a syntax like this:

```scala
//object, label, id
.addVerex(jack, jack.name, jack.address.zip)

//using the name of class as label, and second arg is id
.addVerex(jack,  jack.address.zip)
```

or something like this! I also think having compatibility with all Scala versions `2.10` `2.11` would be nice.

**Comment by joan38** [comment]
See #87

**Comment by joan38** [comment]
Next work:
- Bring back the support for Options again.
- Add support for serialized object.
- Add a `@key("overrided key")` in case someone wants to tie the field to another name.
- `@ignore` to ignore a field.
- Add a `@indexed`

**Pull request merged**
