### PR TITLE
++ Syntax for adding vertex with sugar.

### PR DESCRIPTION
**Pull request by dkrieg**

### CODE REVIEW

**Comment by mpollmeier** [comment]
nice one, thank you!

**Comment by joan38** [comment]
I don't like this syntax because it took me 5-10 min to understand what's happening.

I think we should be careful about the understandability when introducing symbol based functions and not fall into a code that no one understand except yourself.
I take for example: `List("1", "2", "3").foldLeft("")((a, b) => a + b)`
can also be written `(List("1", "2", "3") /: "")((a, b) => a + b)`
But everyone agreed that this syntax is bullshit.
You should watch Martin Odersky speaking about that @ 1:02:30: https://www.parleys.com/tutorial/keynote-scala-style

In Scala `++` is usually a concatenation operator and here we are not concatenating at all.
I would maybe suggest to change for a simple `+` that usually means "add".

**Comment by dkrieg** [comment]
Would you be better with + ?  If we fall back to text then we should just remove it "add" it no better than "addVertex".
````scala
    val g = TinkerGraph.open.asScala
    g + (software, blueprints, _2010)
    g.V.has(blueprints).head <-- dependsOn --- (g + (software, gremlin, _2009))
    g.V.has(gremlin).head <-- dependsOn --- (g + (software, gremlinScala))
    g.V.has(gremlinScala).head <-- createdBy --- (g + (person, mpollmeier))
```
vs 
```scala
    val g = TinkerGraph.open.asScala
    g + (software, blueprints, _2010)
    g.V.has(blueprints).head <-- dependsOn --- g.addVertex(software, Map(gremlin, _2009))
    g.V.has(gremlin).head <-- dependsOn --- g.addVertex(software, Map(gremlinScala))
    g.V.has(gremlinScala).head <-- createdBy --- g.addVertex(person, Map(mpollmeier))
```

**Comment by joan38** [comment]
Yes it would be better with a `+` although I don't really get what's the advantage over `addVertex` except less chars.

I'm not sure to understand this sentence:
"If we fall back to text then we should just remove it "add" it no better than "addVertex"."

Second thing is why did you put those functions in a implicit class? Why not directly in ScalaVertex?

Third thing the `properties: (String, Any)*`:
I don't know if it's good or not but we should agree on one notation and keep this notation across the all API. The user will be confused if he has to switch between the 2 notations.
I personally prefer the explicit Map because it's more clear when reading the code whereas when I read `g + (software, gremlin, _2009)` I have to guess that the first parameter is actually the label and the following is the properties.

**Comment by mpollmeier** [comment]
Good points Joan. You're right, it's not always a good idea to have symbolic names and fold is a good example where it's not. In this case I'm with Daniel though, I think it's great to have a shorter alternative to add a vertex. You're right, `++` is probably not the best choice, but I don't have a problem with `+`.

Re `properties: (String, Any)*` I first had the same thought as you Joan, but when I saw the Spec it made sense, as `"someKey" -> "someValue"` is also a tuple. Your example `g + (software, gremlin, _2009)` wouldn't compile, right? It would have to be `g + (software, (gremlin, _2009))` or better `g + (software, gremlin -> _2009)`
I agree that we should agree on one notation, either tuples or maps. Joan votes for Map. Any preference @dkrieg  @omidb?

**Comment by joan38** [comment]
Agreed on the `+` notation.

In he's case he did:

    val gremlin = blabla -> blublu
    val _2009 = whatever-> everwhat
    g + (software, gremlin, _2009)

that's why it's working.

We can probably add both notation everywhere except in the implicit left and double arrow:
https://github.com/mpollmeier/gremlin-scala/blob/master/gremlin-scala/src/main/scala/gremlin/scala/package.scala#L104

And lastly can we move the introduced function:
https://github.com/mpollmeier/gremlin-scala/blob/master/gremlin-scala/src/main/scala/gremlin/scala/package.scala#L117
in ScalaVertex and remove the implicit class as it is useless here and cause implicit conflict with the `StringLike.+` implicit.

**Comment by dkrieg** [comment]
Here are my thoughts:
First, the following API does not allow me to add T.label -> "something" and "label" -> "something" does not actually cause "something" to be set as the label
```
  def addVertex(properties: Map[String, Any]): ScalaVertex = {
    val v = addVertex()
    v.setProperties(properties)
    v
  }
```
The following + methods does allow me to add T.label -> "something" 
```
  def +(properties: Map[Any, Any]): ScalaVertex =
    graph.addVertex(properties.flatMap(p => List(p._1, p._2)).asInstanceOf[Seq[Object]]: _*)

  def +(properties: (Any, Any)*): ScalaVertex =
    graph.addVertex(properties.flatMap(p => List(p._1, p._2)).asInstanceOf[Seq[Object]]: _*)
```
and for usage comparison:
```
  it("has - sugar 1") {
    def name(n: String) = "name" -> n
    def created(n: Int) = "created" -> n
    def label(n: String) = T.label -> n

    val g = TinkerGraph.open.asScala
    g + (label("software"), name("blueprints"), created(2010))
    g.V.has(name("blueprints")).head <-- "dependsOn" --- (g + (label("software"), name("gremlin"), created(2009)))
    g.V.has(name("gremlin")).head <-- "dependsOn" --- (g + (label("software"), name("gremlinScala")))
    g.V.has(name("gremlinScala")).head <-- "createdBy" --- (g + (label("person"), name("mpollmeier")))

    g.V.toList().size shouldBe 4
    g.V.hasLabel("software").toList().size shouldBe 3
    g.V.hasLabel("person").toList().size shouldBe 1

    g.E.toList().size shouldBe 3
    g.E.hasLabel("dependsOn").toList().size shouldBe 2
    g.E.hasLabel("createdBy").toList().size shouldBe 1
  }

  it("has - sugar 2") {
    def name(n: String) = "name" -> n
    def created(n: Int) = "created" -> n
    def label(n: String) = T.label -> n

    val g = TinkerGraph.open.asScala
    g + Map[Any, Any](label("software"), name("blueprints"), created(2010))
    g.V.has(name("blueprints")).head <-- "dependsOn" --- (g + Map[Any, Any](label("software"), name("gremlin"), created(2009)))
    g.V.has(name("gremlin")).head <-- "dependsOn" --- (g + Map[Any, Any](label("software"), name("gremlinScala")))
    g.V.has(name("gremlinScala")).head <-- "createdBy" --- (g + Map[Any, Any](label("person"), name("mpollmeier")))

    g.V.toList().size shouldBe 4
    g.V.hasLabel("software").toList().size shouldBe 3
    g.V.hasLabel("person").toList().size shouldBe 1

    g.E.toList().size shouldBe 3
    g.E.hasLabel("dependsOn").toList().size shouldBe 2
    g.E.hasLabel("createdBy").toList().size shouldBe 1
  }
```

**Pull request merged**
