### PR TITLE
Add support for Traversal.promise

### PR DESCRIPTION
**Pull request by tolbertam**

### CODE REVIEW

**Comment by tolbertam** [comment]
Added a unit test for it but it's pretty basic and using mock data.  Doing a quick sanity check with a remote graph as I wanted to test the error case (but highly likely that will work fine)

**Comment by tolbertam** [comment]
Looks like scala 2.11 doesn't like this, investigating:

```
[error] /home/travis/build/mpollmeier/gremlin-scala/gremlin-scala/src/main/scala/gremlin/scala/GremlinScala.scala:682: missing parameter type for expanded function
[error] The argument types of an anonymous function must be fully known. (SLS 8.5)
[error] Expected type was: java.util.function.BiConsumer[? >: NewEnd, ? >: Throwable]
[error]     this.traversal.promise(wrapperFun).whenComplete {
```

**Comment by tolbertam** [comment]
I experimented with DSE Graph and it seems to behave well:

```scala
    "execute a traversal asynchronously using promise" in fixture { g =>
      // Basic example that demonstrates chaining asynchronous futures with one another.
      val future: Future[Option[String]] = for {
        createdVertex <- g.addV(Person).property(Name, "marko").promise(_.head)
        name <- g.V(createdVertex.id).value(Name).promise(_.headOption)
      } yield name

      val name = Await.result(future, FiniteDuration(1, SECONDS))
      name shouldEqual Some("marko")
    }

    "encounter a failed traversal asynchronously using promise" in fixture { g =>
      // Basic example that demonstrates that a traversal that encounters an error will fail the resulting exception
      val future: Future[Vertex] = g.V("invalidid").promise(_.head)

      // CompletionException will be raised when awaiting the future
      val thrown = intercept[CompletionException] {
        Await.result(future, FiniteDuration(1, SECONDS))
      }

      // InvalidQueryException should be the cause since this is the error DSE would have emitted
      thrown.getCause shouldBe a[InvalidQueryException]
    }
```

However I encountered two things:

* [TINKERPOP-1671](https://issues.apache.org/jira/browse/TINKERPOP-1671)
* java-driver-dse-graph does not provide a concrete implementation of `RemoteConnection.executeAsync`.  If it did, TINKERPOP-1671 wouldn't have been encountered.

I patched the dse driver locally so it had a concrete implementation (and thus worked around TINKERPOP-1671) and the Future returned from `GremlinScala.promise` failed appropriately.

So the implementation seems to be behaving well, now to make this work for scala 2.11.

**Comment by tolbertam** [comment]
Funny coincidence, I ran into [one of your blog posts](http://www.michaelpollmeier.com/2014/10/12/calling-java-8-functions-from-scala) that got me pointed in the right direction.  I defined a `toJavaBiConsumer` method and use that and it looks like that'll fix things for scala 2.11.  Pushing up a fix shortly.

**Comment by mpollmeier** [comment]
hehe, guess where the inspiration for that post came from :)g
well done, again. thank you!

**Pull request merged**
