### PR TITLE
Implemented a maximum of the Graph interface

### PR DESCRIPTION
**Pull request by joan38**
- Replaced funny arrow char by a real => to avoid issues in Idea
- Implemented a maximum of the Graph interface function in other to keep the user in the Scala world

### CODE REVIEW

**Comment by mpollmeier** [comment]
mmh, I kind of like the unicode arrows... what errors do you get in Idea?

**Comment by joan38** [comment]
Just a presentation issue, not important. I will revert this change then.
How do you write this arrow with your keyboard?

In this PR I wanted to make ScalaGraph to extends Graph but due to this
`addVertex(keyValues: AnyRef*)` we can't.
Anyway I think we need to follow as much as possible the Java
implementation in order to keep the user in the Scala objects.
I will do the same work on ScalaVertex, ScalaEdge and others.

**Comment by joan38** [comment]
I haven't been able to put back the special char back so I'm merging like that and I let you do ?

**Comment by mpollmeier** [comment]
Sure, will do. I just use scalariform btw

**Comment by mpollmeier** [comment]
I just formatted all scala files. With more collaboration we probably need automatically enforced scalariform, which can be done with an sbt plugin.

**Comment by joan38** [comment]
Maybe yeah.
Why do you format the import with spaces like this:

    import java.util.stream.{ Stream ⇒ JStream }

instead of like this:

    import java.util.stream.{Stream ⇒ JStream}

**Comment by mpollmeier** [comment]
That's just the default with scalariform. And it's consistent with the 
formatting of curlies everywhere else, e.g. `List(1, 2, 3) map { _ + 1 }`

**Comment by joan38** [comment]
Yes but that doesn't look like to be consistant with the Scala
conventions...

**Comment by joan38** [comment]
image
Here is the issue with the special chars and Idea

**Comment by mpollmeier** [comment]
wow, that's weired. what operating system are you on? 
what if you open the same file in a different editor?

**Comment by mpollmeier** [comment]
re the conventions: haven't found it in any of the style guides, but all projects I remember of do it that way. 
see e.g. https://github.com/akka/akka/blob/master/akka-testkit/src/test/scala/akka/testkit/AkkaSpec.scala#L9

**Comment by joan38** [comment]
Answer 1: Windows

Answer 2:
Idea is formatting without spaces by default.
But it's true that I haven't been able to find any official doc, so I asked:
http://stackoverflow.com/questions/32459233/scala-multiple-import-formatting

**Comment by joan38** [comment]
I solved the issue of the special char by changing the encoding to UTF-8.

**Comment by mpollmeier** [comment]
that makes sense. Where and how exactly did you make that change? (you know, to help future generations...)

**Comment by joan38** [comment]
image

**Comment by mpollmeier** [comment]
so, you told intellij that this file is utf8?

**Comment by joan38** [comment]
Yes, with the dropdown list where it's written UTF-8 as it was written windows-1252 but this changes only for this file.
I you want to change for the hole project then in Settings you have File Encodings

**Comment by mpollmeier** [comment]
I am not sure but it sounds like Windows doesn't correctly detect that 
this is a UTF-8 encoded file. Are we really in 2015 and still have these 
problems?

On Linux there's a tool `file` that displays information about a file. E.g.
file GremlinScala.scala
GremlinScala.scala: UTF-8 Unicode text

**Comment by joan38** [comment]
Yeah this is ridiculous and we are talking about Windows 10...

**Pull request merged**
