### PR TITLE
Add select by column (keys and values)

### PR DESCRIPTION
**Pull request by To-om**
Add select by column step.

### CODE REVIEW

**Comment by mpollmeier** [comment]
Very nice, thanks for sharing!

I added type annotations in the tests and noticed that for your `extract values from map entry`, selectValues actually resolves the wrong type, leading to a `ClassCastException` if you actually use it. See https://github.com/mpollmeier/gremlin-scala/commit/11daa233cab847041dbe7e49c49ee86436779eb8#diff-6a2fa34f3608ee6cf59f43be5971c02eR191

I didn't look into why that's the case and how to best fix it, wanted to get your feedback first.

**Comment by To-om** [comment]
The test fails because the type parameter of `unfold` is not correct. The `groupBy` step returns a `JMap[String, String]` instead of a `JMap[String,  JCollection[Vertex]]`. The test can be fixed with:
```diff
        .V()
         .hasLabel("software")
         .group(By(__.value(Key[String]("name"))), By(__.in("created").value(Key[String]("name"))))
-        .unfold[JMap.Entry[String, JCollection[Vertex]]]()
+        .unfold[JMap.Entry[String, String]]()
         .selectValues
         .toList
```

The `group` step hasn't a consistent return type:
```
gremlin> g.V().hasLabel('software').group().by("lang").by('name')
==>[java:[lop,ripple]]
gremlin> g.V().hasLabel('software').group().by("lang").by(values('name'))
==>[java:ripple]
gremlin> g.V().hasLabel('software').group().by("lang").by(__.values('name'))
==>[java:ripple]
```
The first query returns a `JMap[String, JCollection[String]]` but the second and the third return a `JMap[String, String]`

Both `by('name')` and `by(values('name'))` has the same modulation type.

I don't know how should be the return type of [group](https://github.com/mpollmeier/gremlin-scala/blob/selectColumn/gremlin-scala/src/main/scala/gremlin/scala/GremlinScala.scala#L417).

**Comment by mpollmeier** [comment]
Yes :( 
Translating your groovy examples to scala, it's obvious how we incorrectly infer the return types:
```
scala> g.V.hasLabel("software").group(By(Key[String]("lang")), By(__.value(Key[String]("name")))).head
res1: java.util.Map[String,java.util.Collection[String]] = {java=ripple}

scala> g.V.hasLabel("software").group(By(Key[String]("lang")), By(Key[String]("name"))).head
res2: java.util.Map[String,java.util.Collection[String]] = {java=[lop, ripple]}
```

The problem is that this only differs for the `values` modulator, not for the `keys` modulator. It's not the only place where we see how little gremlin-java cares about types (which makes gremlin-scala necessary in the first place) 

The only halfway sane solution I can see is to introduce `ByValue[Modulated]` as a duplicate of `By`. Thoughts?

**Comment by mpollmeier** [comment]
To be more precise: 

The `Modulated` type parameter of `ByValue` would be 
* `String` when created with `By(Key[String])` as in the first case
* `java.util.Collection[String]` when created with `By(GremlinScala[String])` as in the second case

And then `group(By[ModulatedKeys], By[ModulatedValues])` would return `GremlinScala[JMap[ModulatedKeys, ModulatedValues]]`

**Comment by To-om** [comment]
I don't see any better solution than what you mention (add a `ByValue` trait). 

I don't understand why the type of `...group().by("lang").by('name')` and the type of `...group().by("lang").by(values('name'))` differ. The documentation doesn't give clear information about that (maybe it is a bug).

**Comment by mpollmeier** [comment]
Looks like a bug to me. Wanna ask on the mailing list?
https://groups.google.com/forum/#!forum/gremlin-users

**Pull request merged**
