### PR TITLE
Improve macro hygiene (qualify class references)

### PR DESCRIPTION
**Pull request by jeremysears**
Improves macro hygiene by using fully qualified class references.
https://docs.scala-lang.org/overviews/quasiquotes/hygiene.html

### CODE REVIEW

**Comment by jeremysears** [comment]
I ran into an issue where a class I was using called Vertex.toCC[DomainEnd] and it wouldn't compile. It turned out that I had imported java.util.List. That caused the List references in the macro to resolve as java.util.List instead of scala.collection.immutable.List. I've gone through and qualified all class references that the macro uses, so that they are unambiguous. This should avoid conflict in where a user has imported a class with the same name as one you chose for a gremlin.scala classes, or for core Scala types.

**Comment by mpollmeier** [comment]
perfect, thank you!

**Comment by mpollmeier** [comment]
note that this will be released automatically, no more need to wait for the next release :)

**Comment by jeremysears** [comment]
I saw the ShiftLeftSecurity/sbt-ci-release-early addition.  That looks convenient.  I'll probably use that at some point.  Thanks for getting that in!  The quick turn-around on releases makes it much easier for me to contribute.  I have a related question about it that I've just posted on your gitter.
https://gitter.im/mpollmeier/gremlin-scala?at=5bc00060435c2a518e909632

Along those lines, I see you've recently started working on the DSL again.  I've done a bunch of work around that, which I'd like to contribute.  Hopefully I can get it in shorty.  I've added a bunch more steps, including many of those you've just added, along with edge support and some Converter enhancements.

**Pull request merged**
