### PR TITLE
Class saving/loading...

### PR DESCRIPTION
**Pull request by joan38**
- Updated Scala versions
- Added Scala reflexion library
- Put the types ScalaEdge, ScalaGraph, ScalaVertex and ScalaElement in separate files for better readability
- Moved package object scala in the package scala according to the convention
- Method save() to save a class in the graph
- Method load() to load a Vertex as an instance of class. This method is wrapped in an implicit object to import in order to be available only when dealing with Vertex (I got the idea from Apache Spark).

### CODE REVIEW

**Comment by mpollmeier** [comment]
Sorry it took such a long time, but I finally got around merging this. As the codebase moved on in the meantime it was the easiest to discard this and apply the changes manually. I mentioned this PR in every commit I made. 
I also added tests and documentation for this - see https://github.com/mpollmeier/gremlin-scala/commit/c7a815290a64e78771a000b4eacd42a39fe6599f for more details

Thank you, much appreciated!

**Comment by joan38** [comment]
Great and no worries for the time it's still in beta anyway...

Although, even if Scala allow it, I think keeping multiple not that much related classes in the same file of 200+ lines is not a good idea as it makes difficult to navigate an understand the code.
I would be curious to hear other points of view on this matter.

That is why I cut down in files like ScalaVertex, ScalaEdge, ScalaElement, ScalaGraph...

**Comment by mpollmeier** [comment]
I've just split up those into their own respective files and cleaned up the imports. Cheers!

**Comment by joan38** [comment]
It looks very nice :+1:

**Pull request closed without merging**
